### ISSUE TITLE
No config flow

### ISSUE THREAD

**Issue by Skeletorjus** [jesserockz/ha-leafspy#1]
## Version of the custom_component
v.0.1.0

## Configuration

```yaml
Installed via HACS

```

## Describe the bug
After the intergration is added, there is no config flow, and no device_tracker is added.
asyncio is not defined, see log.
## Debug log

```text
2020-09-03 08:06:40 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Leaf Spy for leafspy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 309, in async_unload
    result = await component.async_unload_entry(  # type: ignore
  File "/config/custom_components/leafspy/__init__.py", line 54, in async_unload_entry
    await asyncio.gather(
NameError: name 'asyncio' is not defined
2020-09-03 08:06:57 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.leafspy

```

**Comment by jesserockz** [comment]
Thanks for noticing this.

Closed by https://github.com/jesserockz/ha-leafspy/commit/7ceeb9bccb824c42001824999ec0e8222aa364c9
